//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MTL_Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_DVL_INV_PN
    {
        public decimal PART_ID { get; set; }
        public string PART_NO { get; set; }
        public string PRODUCT_NAME { get; set; }
        public string STD_PACK { get; set; }
        public Nullable<decimal> MIN_QTY { get; set; }
        public Nullable<decimal> MAX_QTY { get; set; }
        public string CATEGORY_ID { get; set; }
        public string STATUS { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
    }
}
