//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MTL_Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_DVL_INV_PN_RCV
    {
        public decimal ID { get; set; }
        public string RCV_ID { get; set; }
        public Nullable<decimal> PART_ID { get; set; }
        public Nullable<decimal> RCV_QTY { get; set; }
        public Nullable<System.DateTime> RCV_DATE { get; set; }
        public string STORE_ID { get; set; }
        public string DOC_NO { get; set; }
        public string DOC_FILE_DIR { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
    }
}
